# Generated by Django 4.1.5 on 2023-02-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_room_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
